MBTI API
chaesunbak/vote-system pull request #12
Opened 2024-10-16 00:21 UTC by layout-SY

- CreateMBTI : MBTI DB에 생성
- GetMBTIData : DB에 있는 JSON 형태의 user MBTI
- GetMBTIText : JSON 형태의 user MBTI 문자 형태로 출력
- MBTI_Update : 설문 시 해당 문항으로 MBTI 변동 가능성 추가

## 📋 Pull Request 제목

- 작업 내용 간단 요약

## 📝 변경 사항

- 주요 변경 사항을 간략히 설명해주세요.
- 코드 또는 로직에서 어떻게 변경되었는지 요약하세요.

## ✅ 체크리스트

- [ ] 코드에 주석을 추가했나요?
- [ ] 새로운 기능 또는 버그 수정이 해당 문서에 반영되었나요?
- [ ] 디버그를 위해 작성해둔 log를 지웠나요?
- [ ] 불필요한 코드를 남겨두진 않았나요?

## 📸 변경된 UI나 API 응답 (필요시)

- UI 변경이 있다면 스크린샷이나 관련된 API 응답 결과를 첨부하세요.

## 🚧 주의 사항

- 코드 리뷰 시 알아야 할 점이나 추가로 설명이 필요한 내용이 있다면 적어주세요.

2024-10-16 10:02 UTC, chaesunbak requested changes
.eslintrc.json 
.prettierrc.json

이 두파일은 린트랑 프리티어 설정이여서 삭제하면 안될 것 같습니다.

.prettierrc.json도 깃이그노어에 들어가면 안될 것 같아요

2024-10-16 10:02 UTC, chaesunbak commented on routes/mbti.js
> +router.post('/getMBTIData', GetMBTIData);
루트가 더 restful하면 좋을 것 같아요.

/vote 는 /mbti/vote 를 의미하는건가요 아니면 /vote 로 설문에 투표할때를 의미하는 건가요

2024-10-16 10:02 UTC, chaesunbak commented on Controller/mbtiController.js
> +             ) WHERE userId = ?`;
mbti의 구체적인 정보를 저장하는게 도전적이고 좋은 것 같습니다.

아마 mbti가 필요한 곳이 stats api일 것 같은데, 자주 사용할 거라면 users 테이블 칼럼에서 바로 조회하는 게 좋을 것 같다고 생각했습니다.

저는 두가지 방법을 생각해봤는데요.
(1) users 테이블에 varchar로 저장되는 mbti 칼럼과 JSON으로 저장되는 mbti_detail 칼럼을 추가하는 방식
(2) mbti_detail을 테이블을 따로 분리하는 방식

mbti랑 mbti_detail이 약간 겹친다는 단점이 있긴한데 장점도 있는 것 같은데 어떠신가요

2024-10-17 05:05 UTC, layout-SY commented on Controller/mbtiController.js
> +             ) WHERE userId = ?`;
1번 같은 경우는 회원가입할 때 MBTI 검사를 같이 하는 경우에 맞는 거 같고,
2번 같은 경우는 회원가입 후 별도로 MBTI 검사를 진행할 때 유용할 거 같아서 저는 1번으로 하고
말씀하신 방식대로 컬럼을 두 개로 나눠도 될 거 같다고 생각합니다.

2024-10-17 05:06 UTC, layout-SY commented on routes/mbti.js
> +router.post('/getMBTIData', GetMBTIData);
/mbti/vote를 의미합니다. app.js를 아직 안건드려서 그렇습니다.

2024-10-17 05:39 UTC, closed without merging